name = "deploy-to-cf-workers"
type = "webpack"
account_id = "8995c0f49cdcf57eb54d2c1e52b7d2f3"
zone_id = "29ed9c83c2c78d6967876c4053ec8154"
route = "https://deploy.workers.cloudflare.com/*"

kv-namespaces = [
  { binding = "AUTH_STORE", id = "3cfefdfc6cd34c7b986848720666fb6a", preview_id = "3cfefdfc6cd34c7b986848720666fb6a" }
]

[site]
bucket = "../app/build"

[vars]
CLIENT_ID = "c8375251e295d44406c5"

[env.development]
workers_dev = true

kv-namespaces = [
  { binding = "AUTH_STORE", id = "66830e6b0b5d4c46959763dd787db72f", preview_id = "66830e6b0b5d4c46959763dd787db72f" }
]
